using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Text.Json;
using AFMediaBar.Classes.Models.Credits;
using AFMediaBar.Classes.Services.Updates;
using AFMediaBar.Resources;

namespace AFMediaBar.Classes.Services.Credits;

/// <summary>
/// 开发人员与赞助者名单的读取与缓存服务。
/// The service that reads and caches the developer and sponsor lists.
///
/// 读取顺序（与更新链路同一套思路，只是名单没有哈希兜底）：
/// 1. **缓存**：24 小时内的结果直接用，不联网；
/// 2. **贡献者**：先请求 GitHub 接口（直连，接口主机无法走加速），失败则回退到**仓库里的快照**
///    （raw → jsDelivr → 加速站点）；
/// 3. **赞助名单**：直接读仓库里的 <c>docs/sponsors.json</c>（raw → jsDelivr → 加速站点）；
/// 4. 全部失败时保留上一次的内容，只更新"失败原因"，绝不抛异常给界面。
/// Read order, the same idea as the update path except that these lists have no hash backstop:
/// 1. **cache**: a result younger than 24 hours is used as-is, with no network access;
/// 2. **contributors**: the GitHub API is tried first — directly, because the API host cannot go through an accelerator — and on failure the
///    **snapshot in the repository** takes over (raw, then jsDelivr, then the accelerators);
/// 3. **sponsors**: the repository's <c>docs/sponsors.json</c> is read directly (raw, then jsDelivr, then the accelerators);
/// 4. when everything fails the previous content is kept and only the failure reason changes; nothing is ever thrown at the interface.
///
/// 之所以要快照回退：未认证的 GitHub 接口限流 60 次/小时/IP，而名单本身变化很慢，一份随发布更新的快照能让绝大多数用户
/// 完全不碰那个限额。Release CI 用 <c>tools/update-contributors.ps1</c> 生成快照，并随版本元数据提交审核。
/// The snapshot fallback exists because the unauthenticated GitHub API is limited to 60 requests per hour per IP, while these lists change slowly: a
/// snapshot refreshed with each release keeps almost every user away from that limit. The snapshot is generated by
/// <c>tools/update-contributors.ps1</c> in Release CI and reviewed alongside version metadata.
/// </summary>
public sealed class CreditsService : IDisposable
{
    private readonly AppLogService? _log;
    private readonly UpdateService? _updateService;
    private readonly CreditsCacheStore _cache;
    private readonly HttpClient _httpClient = new() { Timeout = TimeSpan.FromSeconds(15) };
    private readonly SemaphoreSlim _fetchGate = new(1, 1);
    private CancellationTokenSource? _cancellation;
    private bool _disposed;

    /// <summary>当前快照；界面只读它，不自己拼数据。/ The current snapshot; the interface only reads it and never assembles data itself.</summary>
    public CreditsSnapshot Current { get; private set; } = CreditsSnapshot.Empty;

    /// <summary>快照变化时触发（可能在后台线程上）。/ Raised when the snapshot changes; this can be on a background thread.</summary>
    public event Action<CreditsSnapshot>? SnapshotChanged;

    /// <summary>
    /// 创建名单服务。
    /// Creates the credits service.
    /// </summary>
    /// <param name="log">程序日志。/ The application log.</param>
    /// <param name="updateService">更新服务：只为读它当前清单里的加速站点列表，不触发任何更新动作。/ The update service, read only for the accelerator list in its current manifest; no update action is ever triggered from here.</param>
    /// <param name="cache">缓存存储；省略时用默认目录（测试可传临时目录）。/ The cache store, defaulting to the standard directory; tests may pass a temporary one.</param>
    public CreditsService(AppLogService? log, UpdateService? updateService = null, CreditsCacheStore? cache = null)
    {
        _log = log;
        _updateService = updateService;
        _cache = cache ?? new CreditsCacheStore();

        // 先亮出缓存：即使网络完全不可用，用户看到的也是上一次的名单而不是空白页。
        // The cache is shown first: even with no network at all the user sees the previous lists instead of an empty page.
        if (_cache.TryRead() is { } cached)
        {
            Current = new CreditsSnapshot(
                cached.Contributors,
                cached.Sponsors,
                FromCache: true,
                cached.FetchedUtc,
                FailureReason: cached.Partial ? Translations.Get("Credits.Status.PartialCached") : null,
                IsLoading: false,
                ContributorsLoaded: cached.Contributors.Count > 0,
                SponsorsLoaded: cached.Sponsors.Count > 0 || !cached.Partial);
        }
    }

    /// <summary>当前生效的加速站点模板：来自更新清单；清单里没写时由策略使用内置默认列表。/ The accelerator templates in effect: taken from the update manifest, while the policy falls back to the built-in defaults when the manifest says nothing.</summary>
    public IReadOnlyList<string>? Accelerators => _updateService?.CurrentState.Manifest?.Accelerators;

    /// <summary>
    /// 取一次名单；缓存有效且不是手动触发时直接返回，不做任何网络请求。
    /// Fetches the lists once, returning immediately with no network access while the cache is fresh and the call was not manual.
    /// </summary>
    /// <param name="isManual">是否由用户手动触发。/ Whether the user triggered this manually.</param>
    public void RequestRefresh(bool isManual)
    {
        if (_disposed)
        {
            return;
        }

        var now = DateTimeOffset.UtcNow;

        // 覆盖变量在场时等同于手动请求：明确指向某个地址的那一次取数不该被缓存挡住（见 CreditsSourcePolicy.HasAnyOverride）。
        // While an override is in place this counts as a manual request: a fetch explicitly pointed at an address must not be held back by the cache, which is what
        // CreditsSourcePolicy.HasAnyOverride explains.
        var bypassCache = isManual || CreditsSourcePolicy.HasAnyOverride;
        if (!CreditsCachePolicy.ShouldFetch(Current.FetchedUtc, now, bypassCache, Current.IsPartial))
        {
            return;
        }

        if (CreditsSourcePolicy.HasAnyOverride)
        {
            _log?.Info(
                "Credits",
                $"使用覆盖地址（提交者快照 contributors snapshot={CreditsSourcePolicy.ResolveOverride(CreditsSourcePolicy.ContributorsSnapshotUrlOverrideVariable)}，" +
                $"赞助名单 sponsors={CreditsSourcePolicy.ResolveOverride(CreditsSourcePolicy.SponsorsUrlOverrideVariable)}）");
        }

        _cancellation?.Cancel();
        var cancellation = new CancellationTokenSource();
        _cancellation = cancellation;

        Publish(Current with { IsLoading = true });

        // 在后台线程执行：这一页可能在窗口刚打开时构造，网络请求绝不能挡在构造路径上。
        // Runs on a background thread: this page can be constructed while a window is opening, and a network request must never sit on that path.
        _ = Task.Run(() => FetchAsync(isManual, cancellation), CancellationToken.None);
    }

    /// <inheritdoc />
    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;
        _cancellation?.Cancel();
        _cancellation?.Dispose();
        _cancellation = null;
        _fetchGate.Dispose();
        _httpClient.Dispose();
    }

    private async Task FetchAsync(bool isManual, CancellationTokenSource cancellation)
    {
        var token = cancellation.Token;
        await _fetchGate.WaitAsync(token).ConfigureAwait(false);
        try
        {
            var contributors = Current.Contributors;
            var sponsors = Current.Sponsors;
            var failures = new List<string>();
            var contributorsLoaded = Current.ContributorsLoaded;
            var sponsorsLoaded = Current.SponsorsLoaded;
            var fetchedSomething = false;

            var loadedContributors = await LoadContributorsAsync(token).ConfigureAwait(false);
            if (loadedContributors.Contributors is { Count: > 0 })
            {
                contributors = loadedContributors.Contributors;
                contributorsLoaded = true;
                fetchedSomething = true;
            }
            else if (loadedContributors.FailureReason is { } contributorFailure && contributors.Count == 0)
            {
                failures.Add(contributorFailure);
            }

            var loadedSponsors = await LoadSponsorsAsync(token).ConfigureAwait(false);
            if (loadedSponsors.Sponsors is not null)
            {
                sponsors = loadedSponsors.Sponsors;
                sponsorsLoaded = true;
                fetchedSomething = true;
            }
            else if (loadedSponsors.FailureReason is { } sponsorFailure)
            {
                failures.Add(sponsorFailure);
            }

            if (!fetchedSomething)
            {
                var reason = failures.Count > 0
                    ? string.Join(" ", failures)
                    : null;
                _log?.Warn("Credits", $"名单获取失败: {reason}");
                Publish(Current with { IsLoading = false, FailureReason = reason });
                return;
            }

            var fetchedUtc = DateTimeOffset.UtcNow;

            // 只取到一部分时也要写缓存（否则已取到的那半份会被丢掉），但要标成"不完整"：
            // 缓存时效据此从 24 小时缩到 1 小时，没取到的那份名单因此不会被一整天的缓存挡住。
            // A partial result is cached as well — otherwise the half that did arrive would be thrown away — but it is marked incomplete, which shortens the cache
            // from 24 hours to one; the list that failed therefore never gets stuck behind a whole day of cache.
            var isPartial = failures.Count > 0;
            _cache.TryWrite(contributors, sponsors, fetchedUtc, isPartial);
            Publish(new CreditsSnapshot(
                contributors,
                sponsors,
                FromCache: false,
                fetchedUtc,
                FailureReason: failures.Count > 0 ? string.Join(" ", failures) : null,
                IsLoading: false,
                ContributorsLoaded: contributorsLoaded,
                SponsorsLoaded: sponsorsLoaded));

            _log?.Info(
                "Credits",
                $"名单已更新（{contributors.Count} 位贡献者 contributors，{sponsors.Count} 位赞助者 sponsors，" +
                $"不完整 partial={isPartial}，手动 manual={isManual}）");
        }
        catch (OperationCanceledException)
        {
            Publish(Current with { IsLoading = false });
        }
        catch (Exception exception)
        {
            // 关于页的名单只是署名，任何失败都不该让页面出错，记一行即可。
            // These lists are attribution only, so no failure here should break the page; one log line is enough.
            _log?.Warn("Credits", $"名单获取异常: {exception.Message}");
            Publish(Current with { IsLoading = false, FailureReason = exception.Message });
        }
        finally
        {
            _fetchGate.Release();
            if (ReferenceEquals(_cancellation, cancellation))
            {
                _cancellation = null;
            }

            cancellation.Dispose();
        }
    }

    private async Task<CreditsListParseResult> LoadContributorsAsync(CancellationToken cancellationToken)
    {
        string? firstFailure = null;

        foreach (var endpoint in CreditsSourcePolicy.BuildContributorsApiPlan())
        {
            var text = await ReadEndpointAsync(endpoint, cancellationToken).ConfigureAwait(false);
            if (text is null)
            {
                continue;
            }

            var parsed = CreditsJsonParser.ParseContributors(text);
            if (parsed.Succeeded)
            {
                _log?.Info("Credits", $"贡献者取自接口（{parsed.Contributors!.Count}）");
                return parsed;
            }

            firstFailure ??= parsed.FailureReason;
        }

        // 接口不可用（限流、无网络、主机被墙）时读仓库快照：它随发布更新，因此内容最多旧一次发布。
        // When the API is unavailable — rate limited, offline, or the host is unreachable — the repository snapshot is read instead: it is refreshed
        // with each release, so its content is at most one release behind.
        foreach (var endpoint in CreditsSourcePolicy.BuildContributorsSnapshotPlan(Accelerators))
        {
            var text = await ReadEndpointAsync(endpoint, cancellationToken).ConfigureAwait(false);
            if (text is null)
            {
                continue;
            }

            var parsed = CreditsJsonParser.ParseContributors(text);
            if (parsed.Succeeded)
            {
                _log?.Info("Credits", $"贡献者取自仓库快照（{parsed.Contributors!.Count}）");
                return parsed;
            }

            firstFailure ??= parsed.FailureReason;
        }

        return CreditsListParseResult.Failure(firstFailure ?? string.Empty);
    }

    private async Task<CreditsListParseResult> LoadSponsorsAsync(CancellationToken cancellationToken)
    {
        string? firstFailure = null;
        foreach (var endpoint in CreditsSourcePolicy.BuildSponsorsPlan(Accelerators))
        {
            var text = await ReadEndpointAsync(endpoint, cancellationToken).ConfigureAwait(false);
            if (text is null)
            {
                continue;
            }

            var parsed = CreditsJsonParser.ParseSponsors(text);
            if (parsed.Succeeded)
            {
                return parsed;
            }

            firstFailure ??= parsed.FailureReason;
        }

        return CreditsListParseResult.Failure(firstFailure ?? string.Empty);
    }

    private async Task<string?> ReadEndpointAsync(string endpoint, CancellationToken cancellationToken)
    {
        try
        {
            // 与更新清单一致：验收时可以指向本地文件，从而在没有网络的情况下走完整条链路。
            // Matching the update manifest: acceptance runs may point this at a local file and exercise the whole path without a network.
            if (File.Exists(endpoint))
            {
                return await File.ReadAllTextAsync(endpoint, cancellationToken).ConfigureAwait(false);
            }

            using var request = new HttpRequestMessage(HttpMethod.Get, endpoint);
            request.Headers.UserAgent.ParseAdd("AFMediaBar-Credits");
            request.Headers.Accept.ParseAdd("application/vnd.github+json");
            request.Headers.CacheControl = new System.Net.Http.Headers.CacheControlHeaderValue { NoCache = true };
            using var response = await _httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);
            if (!response.IsSuccessStatusCode)
            {
                Debug.WriteLine($"[Credits] {endpoint} returned {(int)response.StatusCode}");
                return null;
            }

            return await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
        }
        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception exception) when (exception is HttpRequestException or TaskCanceledException or IOException or UnauthorizedAccessException)
        {
            Debug.WriteLine($"[Credits] {endpoint} failed: {exception.Message}");
            return null;
        }
    }

    private void Publish(CreditsSnapshot snapshot)
    {
        Current = snapshot;
        SnapshotChanged?.Invoke(snapshot);
    }

    /// <summary>解析一份名单文本；仅供测试与诊断使用。/ Parses one list text; for tests and diagnostics only.</summary>
    /// <param name="json">JSON 文本。/ JSON text.</param>
    /// <returns>解析结果。/ The parse result.</returns>
    internal static CreditsListParseResult ParseForDiagnostics(string json)
    {
        using var document = JsonDocument.Parse(json);
        _ = document;
        return document.RootElement.TryGetProperty("sponsors", out _)
            ? CreditsJsonParser.ParseSponsors(json)
            : CreditsJsonParser.ParseContributors(json);
    }
}
